---
behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0005
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      gail:
        strength: 0.05
        demo_path: Assets/Demonstrations/RegTech.demo
    behavioral_cloning:
      strength: 0.2
      demo_path: Assets/Demonstrations/RegTech.demo
    time_horizon: 64
    max_steps: 10000000
    summary_freq: 5000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change: 100000

